services:
    mysql-server:
        image: mysql:8.4
        platform: linux/x86_64 # thêm lệnh này để chạy được trên Mac M1, nếu lỗi trên chip Intel thì xóa ra
        ports:
            - 3399:3306 # nếu muốn đổi thì chỉ cần đổi số 3399, không được đổi 3306
        restart: always
        volumes:
            - ./mysql/data:/var/lib/mysql # nếu để dòng này thì dòng bên dưới sẽ không có tác dụng
            - ./mysql/sql/:/docker-entrypoint-initdb.d/
        environment:
             MYSQL_ROOT_PASSWORD: root
             MYSQL_DATABASE: nms2
             MYSQL_USER: user
             MYSQL_PASSWORD: user
            
    web:
        build: ./www
        restart: always
        ports:
            - 8080:80 # nếu muốn đổi thì chỉ được đổi số 8080
        volumes:
            - ./www:/var/www/html/
        depends_on:
            - "mysql-server"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8888:80
        restart: always
        environment:
            - PMA_HOST=mysql-server
        depends_on:
            - "mysql-server"

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - "1026:1025"
            - "8025:8025"
        restart: always